services:
  identityproviderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  catalogdb:
    image: mongo:latest

  advertdb:
    image: mongo:latest

  documentmetadatadb:
    image: mongo:latest

  notificationdb:
    image: mongo:latest

  subscriptiondb:
    image: mongo:latest

  distributedcache:
    image: redis

  messagebroker:
    image: rabbitmq:3-management

  yarpapigatewaydesktop:
    image: ${DOCKER_REGISTRY-}yarpapigatewaydesktop
    build:
      context: .
      dockerfile: backend/ApiGateways/YarpApiGatewayDesktop/Dockerfile

  identityprovider.api:
    image: ${DOCKER_REGISTRY-}identityproviderapi
    build:
      context: .
      dockerfile: backend/Services/IdentityProvider/IdentityProvider.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: backend/Services/Catalog/Catalog.API/Dockerfile

  advert.api:
    image: ${DOCKER_REGISTRY-}advertapi
    build:
      context: .
      dockerfile: backend/Services/Advert/Advert.API/Dockerfile

  documentstorage.api:
    image: ${DOCKER_REGISTRY-}documentstorageapi
    build:
      context: .
      dockerfile: backend/Services/DocumentStorage/DocumentStorage.API/Dockerfile

  documentmetadata.api:
    image: ${DOCKER_REGISTRY-}documentmetadataapi
    build:
      context: .
      dockerfile: backend/Services/DocumentMetadata/DocumentMetadata.API/Dockerfile

  notification.api:
    image: ${DOCKER_REGISTRY-}notificationapi
    build:
      context: .
      dockerfile: backend/Services/Notification/Notification.API/Dockerfile

  subscription.api:
    image: ${DOCKER_REGISTRY-}subscriptionapi
    build:
      context: .
      dockerfile: backend/Services/Subscription/Subscription.API/Dockerfile

volumes:
  mongodb_catalog:
  mongodb_advert:
  mongodb_notification:
  mongodb_subscription:
  mongodb_documentmetadata: