services:
  identityproviderdb:
    container_name: identityproviderdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SwN12345678
      - MSSQL_PID=Express
    restart: always
    ports:
      - "1433:1433"

  catalogdb:
    container_name: catalogdb
    environment:
      - MONGO_INITDB_DATABASE=CatalogDb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_catalog:/data/db

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  identityprovider.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=identityproviderdb;Database=IdentityProviderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - identityproviderdb
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Redis=distributedcache:6379
      - MongoSettings__ConnectionString=mongodb://root:example@catalogdb:27017
      - MongoSettings__DatabaseName=CatalogDb
    depends_on:
      - catalogdb
      - distributedcache
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
